### ISSUE TITLE
How to set the style of other controls

### ISSUE THREAD

**Issue by 860000023** [Yet-Zio/FramelessWindow#3]
First of all, thank you for your open source. I just learned Qt not long ago. I ran your test example and the effect was great. But I encountered a problem. I wanted to set up QSS for more ui controls. But when I use
```
ui->setupUi(this);
QFile file(":/darkstyle.qss");
if (file.open(QFile::ReadOnly)) {
QString styleSheet = QLatin1String(file.readAll());
setStyleSheet(styleSheet); // Set the read content as the global style sheet
file.close();
}```, 

comment out
setStyleSheet(".MainWindow{"
"background-color: #616161;"
"}"); 
The main body of the window is transparent. 
I don't know how I should modify it, 
because your example only has one way to change the 
style of a PUSHBUTTON. If you change it one by one, 
this is definitely not good. If you can, I hope you can 
Give me some tips.

**Comment by Yet-Zio** [comment]
how are you setting the background color in your .qss file?

> I don't know how I should modify it, 
> because your example only has one way to change the 
> style of a PUSHBUTTON.

Uh, did you try setting the styles of pushbutton within the .qss file itself like for example:

darkstyle.qss
```css
.MainWindow{
 background-color: #616161;
}

QPushButton{
 // attributes you want to provide
}
```

**Comment by 860000023** [comment]
Sorry, I made a stupid mistake. My qss file was empty. Everything works fine now.
